# Generated by Django 3.2 on 2021-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('recipe', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='posts/')),
            ],
        ),
    ]
